// Email notification using NodeMCU (ESP8266) or ESP32 with Ultra-Sonic sensor and Blynk application.
// This code is created by Prince Kumar Kushwaha

#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

//pins define
const int trigPin = D5;
const int echoPin = D6;
const int buzzerPin = D7;

long duration;
int distance;

char auth[] = "****************************";  //Enter the aoth code generated by Blynk App.

char ssid[] = "Wifi_name";      //Enter your SSID name
char pass[] = "wifi_password";  //Enter your SSID passwaord


void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  Blynk.begin(auth, ssid, pass);
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  pinMode(buzzerPin, OUTPUT);
}

void buzzer() {
    digitalWrite(buzzerPin, HIGH);
    delay(1000);
    digitalWrite(buzzerPin, LOW);
    delay(1000);
}

void loop() {
  // put your main code here, to run repeatedly:
  Blynk.run();
  digitalWrite(trigPin, LOW);
  delayMicroseconds(10);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  //distance in cm
  distance = duration * 0.0340 / 2;
  Blynk.virtualWrite(V5, distance);

  if (distance <= 20) {
    Blynk.email("prince61299@gmail.com", "ESP8266 Alert", "Distance <=10");
    Blynk.notify("ESP8266 alert -> distance <= 10");
    buzzer();
  }
  Serial.print("Distance: ");
  Serial.println(distance);
}
